### ISSUE TITLE
Убери бинарники из проекта

### ISSUE THREAD

**Issue by MWGuy** [KRypt0nn/VoidFramework#1]
Бинарники в репозитории == нулевая одекватность данного проекта

**Comment by FlightBlaze** [comment]
Полностью поддерживаю!

**Comment by KRypt0nn** [comment]
Бинарники будут, причины очевидны. Планов по их удалению нет. Свободны

**Comment by MWGuy** [comment]
Бинарники на гите очень плохая практика, по этому не вижу причины добавить суда сборку этих бинарников из исходного кода
